"""Retention — drop old episodes so a homelab disk does not fill up.

Disabled by default. Two independent limits apply, and an episode is removed if
either says so: an age cap and a total-count cap.

Scope. By default only *ingested* episodes are eligible. Those are produced
automatically and can be regenerated by requeuing the entry, whereas an episode
added by hand with `vocast add` was a deliberate act and is not reproducible
from any feed. Set `include_manual: true` to sweep everything.

The database row always survives. It is the deduplication guard, so deleting it
would let the next poll rediscover the article and synthesize it again --
exactly the loop retention is meant to prevent. Rows are marked `expired`
instead.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path

from ..library import LibraryEntry, list_entries
from .config import RetentionConfig
from .logs import get_logger, kv
from .repository import EntryRepository
from .timeutils import from_iso, utcnow

log = get_logger("retention")


@dataclass
class RetentionReport:
    removed: list[str] = field(default_factory=list)
    freed_bytes: int = 0
    refused: list[tuple[str, str]] = field(default_factory=list)

    @property
    def count(self) -> int:
        return len(self.removed)


class Retention:
    def __init__(
        self,
        *,
        entries: EntryRepository,
        config: RetentionConfig,
        library_path: Path,
        include_manual: bool = False,
    ) -> None:
        self._entries = entries
        self._config = config
        self._library_path = Path(library_path)
        self._include_manual = include_manual

    def apply(
        self, *, now: datetime | None = None, dry_run: bool = False
    ) -> RetentionReport:
        report = RetentionReport()
        if not self._config.enabled:
            return report

        moment = now or utcnow()
        eligible = self._eligible()
        doomed = self._select(eligible, moment)

        for entry in doomed:
            self._remove(entry, report, dry_run=dry_run)
        if report.removed:
            log.info(
                "retention removed episodes %s",
                kv(
                    count=report.count,
                    freed_kb=report.freed_bytes // 1024,
                    dry_run=dry_run,
                ),
            )
        return report

    # -- selection ---------------------------------------------------------

    def _eligible(self) -> list[LibraryEntry]:
        """Library entries retention is allowed to touch, newest first."""
        ingested = {
            episode.episode_id: episode
            for episode in self._entries.published_episodes()
        }
        entries = list_entries()
        if self._include_manual:
            return entries
        return [entry for entry in entries if entry.id in ingested]

    def _select(
        self, eligible: list[LibraryEntry], now: datetime
    ) -> list[LibraryEntry]:
        doomed: dict[str, LibraryEntry] = {}

        if self._config.max_age_days is not None:
            cutoff = now - timedelta(days=self._config.max_age_days)
            for entry in eligible:
                synthesized = from_iso(entry.synthesized_at)
                if synthesized is not None and synthesized < cutoff:
                    doomed[entry.id] = entry

        if self._config.max_episodes is not None:
            # `eligible` is newest-first, so everything past the cap is surplus.
            for entry in eligible[self._config.max_episodes :]:
                doomed[entry.id] = entry

        return list(doomed.values())

    # -- removal -----------------------------------------------------------

    def _remove(
        self, entry: LibraryEntry, report: RetentionReport, *, dry_run: bool
    ) -> None:
        directory = entry.dir()
        if not self._is_inside_library(directory):
            # Never follow a suspicious path out of the library.
            reason = f"{directory} is outside the library at {self._library_path}"
            report.refused.append((entry.id, reason))
            log.error(
                "retention refused to delete %s", kv(episode_id=entry.id, reason=reason)
            )
            return

        size = _directory_size(directory)
        if not dry_run:
            try:
                shutil.rmtree(directory)
            except OSError as exc:
                report.refused.append((entry.id, str(exc)))
                log.warning(
                    "retention could not delete %s",
                    kv(episode_id=entry.id, error=exc),
                )
                return
            self._expire_row(entry.id)

        report.removed.append(entry.id)
        report.freed_bytes += size

    def _expire_row(self, episode_id: str) -> None:
        tracked = self._entries.find_by_episode_id(episode_id)
        if tracked is not None:
            self._entries.expire(tracked.id)

    def _is_inside_library(self, directory: Path) -> bool:
        try:
            resolved = directory.resolve()
            root = self._library_path.resolve()
        except OSError:
            return False
        return resolved != root and resolved.is_relative_to(root)


def _directory_size(directory: Path) -> int:
    total = 0
    if not directory.exists():
        return 0
    for path in directory.rglob("*"):
        if path.is_file():
            try:
                total += path.stat().st_size
            except OSError:
                continue
    return total
